"""add kr field on support card

Revision ID: 58fdad9fd1c2
Revises: be5119c0c923
Create Date: 2021-04-04 05:09:19.830043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fdad9fd1c2'
down_revision = 'be5119c0c923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_card', sa.Column('card_name_kr', sa.String(length=100), nullable=True))
    op.add_column('support_card', sa.Column('card_type_kr', sa.String(length=100), nullable=True))
    op.add_column('support_card', sa.Column('second_name_kr', sa.String(length=200), nullable=True))
    op.execute("""
    UPDATE support_card SET card_name_kr=card_name;
    """)
    op.execute("""
    UPDATE support_card SET card_type_kr=card_type;
    """)
    op.execute("""
    UPDATE support_card SET second_name_kr=second_name;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_card', 'second_name_kr')
    op.drop_column('support_card', 'card_type_kr')
    op.drop_column('support_card', 'card_name_kr')
    # ### end Alembic commands ###
