"""add kr field on event

Revision ID: 73ee085b07b7
Revises: be5119c0c923
Create Date: 2021-04-04 05:11:18.238152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73ee085b07b7'
down_revision = 'be5119c0c923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_event', sa.Column('title_kr', sa.String(length=100), nullable=True))
    op.add_column('card_event_choice', sa.Column('effect_kr', mysql.MEDIUMTEXT(), nullable=True))
    op.add_column('card_event_choice', sa.Column('title_kr', sa.String(length=100), nullable=True))

    op.execute("""
    UPDATE card_event SET title_kr=title;
    """)
    op.execute("""
    UPDATE card_event_choice SET effect_kr=effect;
    """)
    op.execute("""
    UPDATE card_event_choice SET title_kr=title;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_event_choice', 'title_kr')
    op.drop_column('card_event_choice', 'effect_kr')
    op.drop_column('card_event', 'title_kr')
    # ### end Alembic commands ###
