"""add some skill type

Revision ID: e3ddfb8988a7
Revises: 73ee085b07b7
Create Date: 2021-05-01 23:45:55.073573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ddfb8988a7'
down_revision = '73ee085b07b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_buff_type',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('지구력', '가속도', '속도', '스태미너', '지능', '근성', '스피드', '파워', '속도 감소', '스타트', '도발', '포지션', '시야', '시야 방해', '스태미너 방해', '피지컬', name='skillbufftypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skill_distance_type',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('단거리', '마일', '중거리', '장거리', '더트', name='skilldistancetypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skill_grade',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('노말', '레어', '고유', name='skillgradeenum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skill_operation_type',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('도주', '선행', '선입', '후입', name='skilloperationtypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('skill', sa.Column('buff_type_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('distance_type_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('operation_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_skill_buff_type_id'), 'skill', ['buff_type_id'], unique=False)
    op.create_index(op.f('ix_skill_distance_type_id'), 'skill', ['distance_type_id'], unique=False)
    op.create_index(op.f('ix_skill_grade_id'), 'skill', ['grade_id'], unique=False)
    op.create_index(op.f('ix_skill_operation_type_id'), 'skill', ['operation_type_id'], unique=False)
    op.create_foreign_key(None, 'skill', 'skill_grade', ['grade_id'], ['uuid'])
    op.create_foreign_key(None, 'skill', 'skill_distance_type', ['distance_type_id'], ['uuid'])
    op.create_foreign_key(None, 'skill', 'skill_operation_type', ['operation_type_id'], ['uuid'])
    op.create_foreign_key(None, 'skill', 'skill_buff_type', ['buff_type_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_index(op.f('ix_skill_operation_type_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_grade_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_distance_type_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_buff_type_id'), table_name='skill')
    op.drop_column('skill', 'operation_type_id')
    op.drop_column('skill', 'grade_id')
    op.drop_column('skill', 'distance_type_id')
    op.drop_column('skill', 'buff_type_id')
    op.drop_table('skill_operation_type')
    op.drop_table('skill_grade')
    op.drop_table('skill_distance_type')
    op.drop_table('skill_buff_type')
    # ### end Alembic commands ###
